//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_CangTienSa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chiTietPhieuNhap
    {
        public string maChiTietPhieuNhap { get; set; }
        public string maPhieuNhap { get; set; }
        public string maContainer { get; set; }
        public string moTa { get; set; }
    
        public virtual container container { get; set; }
        public virtual phieuNhap phieuNhap { get; set; }
    }
}
