//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_CangTienSa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chiTietKho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chiTietKho()
        {
            this.containers = new HashSet<container>();
        }
    
        public string maChiTietKho { get; set; }
        public string maKho { get; set; }
        public double sucChuaToiDa { get; set; }
        public double tonKho { get; set; }
        public string trangThaiChiTietKho { get; set; }
        public System.DateTime ngayCapNhatCuoi { get; set; }
        public string moTa { get; set; }
    
        public virtual kho kho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<container> containers { get; set; }
    }
}
