//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_CangTienSa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chiTietDonHang
    {
        public string maChiTietDonHang { get; set; }
        public string maDonHang { get; set; }
        public string maHangHoa { get; set; }
        public double soLuong { get; set; }
        public string donViTinh { get; set; }
        public string chatLuong { get; set; }
        public double donGia { get; set; }
        public Nullable<double> tienLuuKho { get; set; }
        public string moTa { get; set; }
    
        public virtual donHang donHang { get; set; }
        public virtual hangHoa hangHoa { get; set; }
    }
}
