//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_CangTienSa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public donHang()
        {
            this.chiTietDonHangs = new HashSet<chiTietDonHang>();
            this.phieuNhaps = new HashSet<phieuNhap>();
            this.phieuXuats = new HashSet<phieuXuat>();
        }
    
        public string maDonHang { get; set; }
        public string maKhachHang { get; set; }
        public string maNhanVien { get; set; }
        public string tenNguoiGui { get; set; }
        public string tenNguoiNhan { get; set; }
        public string cangDichDen { get; set; }
        public System.DateTime ngayTaoDonHang { get; set; }
        public int thoiGianLuuTru { get; set; }
        public Nullable<System.DateTime> ngayXuatCang { get; set; }
        public Nullable<System.DateTime> ngayNhapCang { get; set; }
        public string trangThaiDonHang { get; set; }
        public string trangThaiThanhToan { get; set; }
        public Nullable<double> tongTien { get; set; }
        public string moTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chiTietDonHang> chiTietDonHangs { get; set; }
        public virtual khachHang khachHang { get; set; }
        public virtual nhanVien nhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phieuNhap> phieuNhaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phieuXuat> phieuXuats { get; set; }
    }
}
