//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_CangTienSa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hangHoa()
        {
            this.chiTietDonHangs = new HashSet<chiTietDonHang>();
        }
    
        public string maHangHoa { get; set; }
        public string maDanhMucHangHoa { get; set; }
        public string tenHangHoa { get; set; }
        public double chiPhiLuuKhoToiThieu { get; set; }
        public string donViTinh { get; set; }
        public string moTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chiTietDonHang> chiTietDonHangs { get; set; }
        public virtual danhMucHangHoa danhMucHangHoa { get; set; }
    }
}
