//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_CangTienSa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khachHang()
        {
            this.donHangs = new HashSet<donHang>();
        }
    
        public string maKhachHang { get; set; }
        public string tenDangNhap { get; set; }
        public string matKhau { get; set; }
        public string tenKhachHang { get; set; }
        public string tenCongTy { get; set; }
        public string maSoThueCongTy { get; set; }
        public System.DateTime ngayDangKy { get; set; }
        public string cccd { get; set; }
        public string diaChiLienLac { get; set; }
        public string sdtKhachHang { get; set; }
        public string email { get; set; }
        public string trangThaiTaiKhoanKhachHang { get; set; }
        public string anhDaiDienKhachHangUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<donHang> donHangs { get; set; }
    }
}
