//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_CangTienSa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kho()
        {
            this.chiTietKhoes = new HashSet<chiTietKho>();
        }
    
        public string maKho { get; set; }
        public string maLoaiKho { get; set; }
        public string tenKho { get; set; }
        public string diaChiKho { get; set; }
        public string trangThaiKho { get; set; }
        public double sucChuaToiDa { get; set; }
        public double tonKho { get; set; }
        public string moTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chiTietKho> chiTietKhoes { get; set; }
        public virtual loaiKho loaiKho { get; set; }
    }
}
