//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_CangTienSa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loaiKho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public loaiKho()
        {
            this.khoes = new HashSet<kho>();
        }
    
        public string maLoaiKho { get; set; }
        public string tenLoaiKho { get; set; }
        public Nullable<int> soLuongKho { get; set; }
        public string moTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kho> khoes { get; set; }
    }
}
