//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_CangTienSa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhanVien()
        {
            this.donHangs = new HashSet<donHang>();
        }
    
        public string maNhanVien { get; set; }
        public string maLoaiNhanVien { get; set; }
        public string tenDangNhap { get; set; }
        public string matKhau { get; set; }
        public string tenHienThi { get; set; }
        public string sdtNhanVien { get; set; }
        public string diaChi { get; set; }
        public string trangThaiTaiKhoanNhanVien { get; set; }
        public System.DateTime thoiGianDangNhapGanNhat { get; set; }
        public string anhDaiDienNhanVienUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<donHang> donHangs { get; set; }
        public virtual vaiTroNhanVien vaiTroNhanVien { get; set; }
    }
}
