//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_CangTienSa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieuXuat
    {
        public string maPhieuXuat { get; set; }
        public string maDonHang { get; set; }
        public string trangThaiXuatHang { get; set; }
        public System.DateTime ngayXuatKho { get; set; }
        public string moTa { get; set; }
    
        public virtual donHang donHang { get; set; }
    }
}
